var webpack = require ('webpack');
var path = require ('path');
module.exports = {
    //debugging ko lage
    devtool: 'inline-source-map', //eval-sourse-map
    entry:{
        'index':'./src/index.js'
    },
    output:{ //path.resolve path.join
    path: path.resolve(__dirname,'dist'),
    filename:'main.js'
},
//loader
module:{
    rules:[//multiple rules //inside create different object 
    { //babel use garera es 6, es 7 es 5, browser compact
    // use babel on which files
    test:/\.js$/, //regex starts with (//) end -> $
    exclude:/node_modules/,
    use:'babel-loader'
}
]
},

//devserver to serve the application, only in development 
devServer:{
    //those content that are not generated by webpack
    contentBase: path.join(__dirname,"public/"),
    port:3000,

    //HMR reloading
    hot:true,
    //to serve webpack files
    publicPath:"http://localhost:3000/dist/"
}
}